credentials:
        username: a_username
        password: aP@ssw0rd
        port: 22

routeriplist:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.2.1
        - 10.1.2.2
        - 10.1.3.1
        - 10.1.3.2
        - 10.1.4.1
        - 10.1.5.1
        - 10.1.5.2
        - 10.1.6.1
        - 10.1.6.2
        - 10.1.7.1
        - 10.1.7.2
        - 10.1.8.1
        - 10.1.11.1
        - 10.1.11.2
        - 10.1.12.1
        - 10.1.12.2
        - 10.1.21.1
        - 10.1.21.2
        - 10.1.22.1
        - 10.1.22.2
        - 10.1.25.1
        - 10.1.25.2
        - 10.1.101.1
        - 10.1.102.1
        - 10.1.103.1
        - 10.1.255.1
        - 10.1.255.2

